language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - apt-get install csh
  - cd cspice_linux_gcc_64bit && csh makeall.csh

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
