language: rust
rust:
  - stable
  - beta
  - nightly

env:
  - SPICE_KERNELS=../../../../data/kernels/

before_install:
  - sudo apt-get install csh

before_script:
  - (cd cspice_linux_gcc_64bit && csh makeall.csh && cd lib && mv cspice.a libcspice.a)

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
