language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get install csh
  - csh cspice_linux_gcc_64bit/makeall.csh
  - (cd cspice_linux_gcc_64bit/lib && ln -s cspice.a libcspice.a)

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
