language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get install csh
  - cd cspice_linux_gcc_64bit && csh makeall.csh
  - ln -s cspice_linux_gcc_64bit/lib/cspice.a cspice_linux_gcc_64bit/lib/libcspice.a

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
